spring:
  application:
    name: intership_demo
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  datasource:
    url: jdbc:postgresql://${POSTGRES_SQL_HOST}:${POSTGRES_SQL_PORT}/${POSTGRES_SQL_DB}
    username: ${POSTGRES_SQL_USERNAME}
    password: ${POSTGRES_SQL_PASSWORD}
  jpa:
    show-sql: ${JPA_SHOW_SQL}
    open-in-view: true
    hibernate:
      ddl-auto: validate

server:
  port: ${SERVER_PORT}
  servlet:
    contextPath: /api
